---
volumes:
  postgres-data:


services:
  postgres:
    container_name: postgresql
    image: "postgres:12.2-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
