name: Python linting and formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black

      - name: Run linting
        run: |
          black --check .

      - name: Run formatting
        run: black .

